### ISSUE TITLE
Repository: Missing Reports - List of Participants in a Program

### ISSUE THREAD

**Issue by mapesa** [APHLK/ePT-Repository#34]
Requirement:
1. List of labs participating in a program (eg Malaria) over a given time period (eg Jan-Dec 2016)
2. County coordinators should be able to list the same for their counties
3. Accompanying bar/column graph to show:
    a. Count of participating labs by (county)
    b. Count of participating labs by program
4. This data/analysis should **not necessarily** be limited to a specific provider.

With these we should be able to answer the following questions:
1. How many labs participated in the EQA of the given time period?
2. How many of these labs are in a specific county?
3. How many labs participated in specific program?
4. Do a side by side comparison with other counties/programs/both.

**Comment by mykhie** [comment]
Sorted
