### ISSUE TITLE
Repository: Missing reports - Utilization reports per county/facility/program

### ISSUE THREAD

**Issue by mapesa** [APHLK/ePT-Repository#36]
Requirement:

1. Side by side comparison showing the number of panels (samples) sent per county/facility/program vs the number of results received (tests done)
2. County Coordinators should see the same data for their county
3. List of labs that did not send back results

**Comment by mykhie** [comment]
are the samples sent from the system?cause this was a repository to gather information from different sources?please clarify
cause if the sample are sent from the system,then we can have then upload/fill results against the samples they received?

**Comment by mapesa** [comment]
Can't fix at the moment for the same reason as #35
