### ISSUE TITLE
Repository: User Roles Functionality Missing

### ISSUE THREAD

**Issue by mapesa** [APHLK/ePT-Repository#41]
This feature should allow for satisfactory answers to the following questions:
1. How do you create user roles? e.g. National QA, County QA, Facility QA, EQA Provider
2. How do you assign system features to the roles? e.g. the Facility QA can only see reports for his/her facility
3. How do you assign system roles to specific users?

**Comment by mykhie** [comment]
basically this has been done...,all those are dependent on the modules,
from the drop drop down of level(roles) while you creating a user
