### ISSUE TITLE
Repository: Add New Contact allows for adding users without emails

### ISSUE THREAD

**Issue by mapesa** [APHLK/ePT-Repository#42]
-  Add New Contact feature under _Repository > PT Providers_ allows for adding new users to the DB who have no emails.
- Seem image trail below

1. 
![list providers](https://cloud.githubusercontent.com/assets/998745/24706482/83f728b4-1a18-11e7-8e9d-7f51e587a6ab.png)

2. 
![list providers contacts](https://cloud.githubusercontent.com/assets/998745/24706540/be1292d6-1a18-11e7-9cbd-62e6a301e236.png)

3. 
![add new provider](https://cloud.githubusercontent.com/assets/998745/24706826/d97598c4-1a19-11e7-9440-8eff2f6b32bc.png)

4. 
![new providers contacts list](https://cloud.githubusercontent.com/assets/998745/24706686/36ddc0dc-1a19-11e7-9e84-5a9175af5147.png)

5. User's so added show up under _Configure > PT Managers_. 
**NB**: the names specified under Contact Name: on screed 3 above appear here in both the firstname and last name field. (At the least this will result in data inconsistency).
![configure](https://cloud.githubusercontent.com/assets/998745/24711518/e45e6e14-1a28-11e7-840c-e5d59df468c0.png)

**Comment by brianvidosh** [comment]
Done
