### ISSUE TITLE
Repository: Updating Provider Contact results in an error

### ISSUE THREAD

**Issue by mapesa** [APHLK/ePT-Repository#43]
Updating a PT Provider contact results in an error

1. 
![update contacts](https://cloud.githubusercontent.com/assets/998745/24706969/78a3fee0-1a1a-11e7-91a8-d5da579aa428.png)

2. 
![contact update error](https://cloud.githubusercontent.com/assets/998745/24706976/81eb232a-1a1a-11e7-8438-f322b37616d3.png)

**Comment by brianvidosh** [comment]
Done
