### ISSUE TITLE
Repository: Graph button is hidden under some resolutions

### ISSUE THREAD

**Issue by mapesa** [APHLK/ePT-Repository#46]
This is a responsive design issue. Since this is an online/web-based application, we'll have no control of the computers/browsers used by the system users. Ensure all buttons are available under **typical desktop resolutions**.

Graphs button is hidden under screen widths between 768 - 991 inclusive: 

1. Less than 768
![screenwidth1](https://cloud.githubusercontent.com/assets/998745/24710735/b1e153a4-1a26-11e7-9fbc-e557e0bd6f1a.png)

2. 768
![screenwidth2](https://cloud.githubusercontent.com/assets/998745/24710744/b5f4ca98-1a26-11e7-86d1-01e2d252dee7.png)

3. 991
![screenwidth3](https://cloud.githubusercontent.com/assets/998745/24710751/bac8054e-1a26-11e7-9b03-2f39b860d686.png)

4. Greater than or equal to 992
![screenwidth4](https://cloud.githubusercontent.com/assets/998745/24710769/c059e806-1a26-11e7-8cfe-a50ef15859c4.png)

**Comment by mykhie** [comment]
fixed
