### ISSUE TITLE
Repository: Create new users should send them an email with login credentials

### ISSUE THREAD

**Issue by mapesa** [APHLK/ePT-Repository#48]
Should apply to all modules.

When an admin creates a new user, the password should not be specified unless its self registration.

![create new user](https://cloud.githubusercontent.com/assets/998745/24854432/1fed3930-1de7-11e7-82d8-f452c32bb42d.png)

1. An email should be sent to the created user preferably with a login link.
2. On first access the user should be prompted to set a password.
3. Find below a sample body for this email:

```
Dear {firstname} {lastname},

You have been granted access to the NPHL Integrated EQA Database application.

Please click the following link to access the application in your computer browser.

If you have received this email in error or have any other queries, please notify the system administrator at info@nphl.or.ke.

Regards,
QA Office,
National Public Health Laboratories.
```

**Comment by brianvidosh** [comment]
The current smtp credentials work. It would be better we test with the actual smtp details that will be used by the users in the production environment.

**Comment by mykhie** [comment]
this has been done and the user get a a six digits alphanumeric password which he is prompted to change on first log in.
