### ISSUE TITLE
Mark import data rows with the exact facility/lab

### ISSUE THREAD

**Issue by mapesa** [APHLK/ePT-Repository#50]
Lab names in imported files need to be mapped to the correct facilities/labs.

Ideally, this should be doable from the import interface.

Short term fix
------
1. Update each row in the import files with the MFL Code for each listed lab
2. Load all MFL codes into the system.
3. Link records to a location/facility/lab using the MFL Code, **not** the lab name.

**Comment by mykhie** [comment]
sorted
