### ISSUE TITLE
Imported Data Upload and Rollback

### ISSUE THREAD

**Issue by mapesa** [APHLK/ePT-Repository#53]
The importing user (PT Providers or QA Managers) should be able to:
1. preview the data imported
2. roll back an import (PT Providers can only roll back their own unconfirmed imports. QA Managers can roll back any)
3. confirm (button) that the data is okay (before it can be accessible from reports)
4. QA Managers should be able to revoke particular imports (ie remove the confirmation flag).

**Comment by mykhie** [comment]
Sorted
